name: Plateaux numériques
description: "Des sites web accessibles pour les villages et petites villes durables d’aujourd’hui et de demain"

github_user: timotheegoguely
github_repo: https://gitlab.com/design-commun/plateaux-numeriques

favicon: favicon.ico
